# repos:
#   - repo: https://github.com/pre-commit/pre-commit-hooks
#     rev: v4.4.0
#     hooks:
#       - id: check-yaml
#         types: [yaml]
#       - id: check-toml
#         types: [toml]
#       - id: end-of-file-fixer
#       - id: trailing-whitespace
#       - id: check-ast
#       - id: check-added-large-files
#         stages: [push]
#         args: [--maxkb=10000]
#   - repo: local
#     hooks:
#       - id: darglint
#         name: darglint
#         entry: darglint
#         language: system
#         types: [python]
#         stages: [manual]
#       - id: linting
#         name: linting
#         entry: make lint
#         language: system
#       - id: formatting
#         name: formatting
#         entry: make format
#         language: system
#       - id: deps
#         name: deps
#         entry: make deps
#         language: system
#   - repo: https://github.com/pre-commit/mirrors-prettier
#     rev: v3.0.3
#     hooks:
#       - id: prettier
repos:
  - repo: local
    hooks:
      - id: check-added-large-files
        name: Check for added large files
        entry: check-added-large-files
        language: system
      - id: check-toml
        name: Check Toml
        entry: check-toml
        language: system
        types: [toml]
      - id: check-yaml
        name: Check Yaml
        entry: check-yaml
        language: system
        types: [yaml]
      - id: darglint
        name: darglint
        entry: darglint
        language: system
        types: [python]
        stages: [manual]
      - id: end-of-file-fixer
        name: Fix End of Files
        entry: end-of-file-fixer
        language: system
        types: [text]
        stages: [commit, push, manual]
      - id: trailing-whitespace
        name: Trim Trailing Whitespace
        entry: trailing-whitespace-fixer
        language: system
        types: [text]
        stages: [commit, push, manual]
      - id: ruff
        name: ruff
        entry: ruff
        language: system
        types: [python]
        require_serial: true
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier