# Workflow for building and deploying sphinx documentation to GitHub Pages
name: Documentation

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main, master]
  # pull_request:
  #   branches: [main, master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-docs:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Set up Python 3.12
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # Upgrade pip
      - name: Upgrade pip
        run: |
          pip install --constraint=.github/workflows/constraints.txt pip
          pip --version

      # Install dependencies
      - name: Install dependencies
        run: |
          pip install -r docs/requirements.txt
          pip install .

      # Build the sphinx api docs
      - name: Sphinx build reference docs
        run: |
          cd docs/
          make apidoc

      # Build the html pages
      - name: Sphinx build html pages
        run: |
          cd docs/
          make html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs/_build/html

  deploy-docs:
    # Add a dependency to the build job
    needs: build-docs

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: {{ "${{" }} steps.deployment.outputs.page_url {{ "}}" }}